#!/usr/bin/env bash
# Checks file characteristics for a given file argument

filename="$1"

if [ -e "$filename" ]; then
    echo "$filename file exists"
    
    if [ -s "$filename" ]; then
        echo "$filename file is not empty"
    else
        echo "$filename file is empty"
    fi
    
    if [ -f "$filename" ]; then
        echo "$filename is a regular file"
    fi
else
    echo "$filename file does not exist"
fi
