#!/usr/bin/env bash
# Script that checks file characteristics of 'school' or the first argument passed

filename="school"
if [ -n "$1" ]; then
    filename="$1"
fi

if [ -e "$filename" ]; then
    echo "$filename file exists"
    
    if [ -s "$filename" ]; then
        echo "$filename file is not empty"
    else
        echo "$filename file is empty"
    fi
    
    if [ -f "$filename" ]; then
        echo "$filename is a regular file"
    fi
else
    echo "$filename file does not exist"
fi
